# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accueil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default=b'Bienvenue sur le site des ateliers des marques(c).')),
            ],
            options={
                'verbose_name_plural': '(p1/Agence) News',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=75)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': '(p2/Portfolio) Books',
            },
        ),
        migrations.CreateModel(
            name='CategorieClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default=b'Cat\xc3\xa9gorie client', max_length=20)),
            ],
            options={
                'verbose_name_plural': '(p4/Clients) Cat\xe9gories client',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, default=b'Client', max_length=20, null=True)),
                ('logo', models.ImageField(upload_to=b'clients/')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='web.CategorieClient')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default=b'Personne \xc3\xa0 contacter', max_length=75)),
                ('contact1', models.TextField(blank=True, default=b'small info', null=True)),
                ('contact2', models.TextField(blank=True, default=b'small info', null=True)),
            ],
            options={
                'verbose_name_plural': '(p5/Contact) Contacts',
            },
        ),
        migrations.CreateModel(
            name='MembreEquipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default=b'Prenom Nom', max_length=30)),
                ('statut', models.CharField(default=b'Job title', max_length=30)),
                ('position', models.IntegerField(choices=[(0, '0-Cach\xe9'), (1, '1-Haut'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20-Bas')], default=None, null=True)),
                ('description', models.TextField(default=b'Parcours personnel')),
            ],
            options={
                'ordering': ['position'],
                'verbose_name_plural': '(p3/Equipe) Membres des ateliers',
            },
        ),
        migrations.CreateModel(
            name='PageBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageGauche', models.ImageField(upload_to=b'books/')),
                ('pageDroite', models.ImageField(upload_to=b'books/')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagebooks', to='web.Book')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoMembre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=b'equipe/')),
                ('membre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='web.MembreEquipe')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='pagebook',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client', to='web.PageBook'),
        ),
    ]
